version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: pub
    directories:
      - /
      - /example
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directories:
      - /android
      - /example/android
    schedule:
      interval: weekly
